package com.gary.mqtthttpbridge;

//import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
//@MapperScan(basePackages = {"com.gary.mqtthttpbridge.mapper"}) //扫描mapper接口所在的包
@SpringBootApplication
public class MqttHttpBridgeApplication {

    public static void main(String[] args) {
        //SpringApplication springApplication = new SpringApplication(MqttHttpBridgeApplication.class);
        SpringApplication.run(MqttHttpBridgeApplication.class, args);
    }

}
